//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOgrenciKayit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCOgrenciKayitEntities : DbContext
    {
        public MVCOgrenciKayitEntities()
            : base("name=MVCOgrenciKayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogr> Ogr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
